export const EMAIL_TEMPLATE = [
  {
    id: 1,
    name: '빈템플릿',
    contents: '빈템플릿 내용입니다.',
    src: 'https://resource.stibee.com/templates/thumbnail/template_4.png',
    text: '{"blocks":[{"key":"1btvc","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}',
  },
  {
    id: 2,
    name: '1번템플릿',
    contents: '1번템플릿 내용입니다.',
    src: 'https://resource.stibee.com/templates/thumbnail/template_1.png',
    text: '{"blocks":[{"key":"9behp","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"3h3ul","text":" ","type":"atomic","depth":0,"inlineStyleRanges":[],"entityRanges":[{"offset":0,"length":1,"key":0}],"data":{}},{"key":"f25e6","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"7o32l","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{"text-align":"start"}},{"key":"4r1dr","text":"CSS로 이미지의 원하는 부분만 잘라서 보여주는 방법 (Image Clipping)","type":"header-three","depth":0,"inlineStyleRanges":[{"offset":0,"length":46,"style":"color-rgb(51,51,51)"},{"offset":0,"length":46,"style":"bgcolor-rgb(255,255,255)"},{"offset":0,"length":46,"style":"fontfamily-sans-serif"},{"offset":0,"length":46,"style":"color-rgb(22,22,22)"},{"offset":0,"length":46,"style":"fontsize-2.143em"},{"offset":0,"length":46,"style":"fontfamily-AppleSDGothicNeo-Bold"},{"offset":0,"length":46,"style":"BOLD"},{"offset":0,"length":46,"style":"fontsize-24"}],"entityRanges":[],"data":{"margin-left":"0px"}},{"key":"5fvm2","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{"text-align":"start"}},{"key":"2da4","text":"CSS로 이미지의 원하는 부분만 잘라서 보여주는 방법 (Image Clipping)","type":"unstyled","depth":0,"inlineStyleRanges":[{"offset":0,"length":46,"style":"color-rgb(51,51,51)"},{"offset":0,"length":46,"style":"bgcolor-rgb(255,255,255)"},{"offset":0,"length":46,"style":"fontsize-13"},{"offset":0,"length":46,"style":"fontfamily-sans-serif"},{"offset":0,"length":46,"style":"bgcolor-rgb(238,238,238)"},{"offset":0,"length":46,"style":"fontsize-16"},{"offset":0,"length":46,"style":"fontfamily-AppleSDGothicNeo-Bold"}],"entityRanges":[],"data":{}},{"key":"7s0ks","text":"css를 활용하여 하나의 이미지에서 원하는 부분만 잘라서 보여주는 방법을 소개 해드릴까 합니다. ","type":"unstyled","depth":0,"inlineStyleRanges":[{"offset":1,"length":53,"style":"color-rgb(51,51,51)"},{"offset":1,"length":53,"style":"bgcolor-rgb(255,255,255)"},{"offset":1,"length":53,"style":"fontsize-13"},{"offset":1,"length":53,"style":"fontfamily-sans-serif"},{"offset":1,"length":53,"style":"fontsize-16"},{"offset":1,"length":53,"style":"fontsize-11pt"}],"entityRanges":[],"data":{"margin-left":"0px"}},{"key":"7l5hi","text":"위 방법은 Image Clipping 이라는 기술인데요 background-image 태그를 사용하지 않고 img 태그를 이용한","type":"unstyled","depth":0,"inlineStyleRanges":[{"offset":0,"length":71,"style":"color-rgb(51,51,51)"},{"offset":0,"length":71,"style":"bgcolor-rgb(255,255,255)"},{"offset":0,"length":71,"style":"fontsize-13"},{"offset":0,"length":71,"style":"fontfamily-sans-serif"},{"offset":0,"length":71,"style":"fontsize-16"},{"offset":0,"length":71,"style":"fontsize-11pt"}],"entityRanges":[],"data":{"margin-left":"0px"}},{"key":"71cgg","text":"방법으로 하였습니다.","type":"unstyled","depth":0,"inlineStyleRanges":[{"offset":0,"length":11,"style":"color-rgb(51,51,51)"},{"offset":0,"length":11,"style":"bgcolor-rgb(255,255,255)"},{"offset":0,"length":11,"style":"fontsize-13"},{"offset":0,"length":11,"style":"fontfamily-sans-serif"},{"offset":0,"length":11,"style":"fontsize-16"},{"offset":0,"length":11,"style":"fontsize-11pt"}],"entityRanges":[],"data":{"margin-left":"0px"}},{"key":"d84n5","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"fdk5f","text":"background-image 를 활용하게 되면 익스플로러에서 인쇄를 할때 이미지가 출력이 안될 수 있다는 단점이 있습니다만","type":"unstyled","depth":0,"inlineStyleRanges":[{"offset":0,"length":69,"style":"color-rgb(51,51,51)"},{"offset":0,"length":69,"style":"bgcolor-rgb(255,255,255)"},{"offset":0,"length":69,"style":"fontsize-13"},{"offset":0,"length":69,"style":"fontfamily-sans-serif"},{"offset":0,"length":69,"style":"fontsize-16"},{"offset":0,"length":69,"style":"fontsize-11pt"}],"entityRanges":[],"data":{"margin-left":"0px"}},{"key":"8k9bi","text":"페이지를 모두 출력해서 사용 하는 것은 아니니 크게 상관은 없겠죠? ","type":"unstyled","depth":0,"inlineStyleRanges":[{"offset":0,"length":37,"style":"color-rgb(51,51,51)"},{"offset":0,"length":37,"style":"bgcolor-rgb(255,255,255)"},{"offset":0,"length":37,"style":"fontsize-13"},{"offset":0,"length":37,"style":"fontfamily-sans-serif"},{"offset":0,"length":37,"style":"fontsize-16"},{"offset":0,"length":37,"style":"fontsize-11pt"}],"entityRanges":[],"data":{"margin-left":"0px"}}],"entityMap":{"0":{"type":"IMAGE","mutability":"MUTABLE","data":{"src":"https://www.codingfactory.net/wp-content/uploads/abc.jpg","height":"300px","width":"450px","alt":"ALT"}}}}',
  },
  {
    id: 3,
    name: '3번템플릿',
    contents: '3번템플릿 내용입니다.',
    src: 'https://resource.stibee.com/templates/thumbnail/tem_news09.png',
    text: '{"blocks":[{"key":"9behp","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"82b35","text":" ","type":"atomic","depth":0,"inlineStyleRanges":[],"entityRanges":[{"offset":0,"length":1,"key":0}],"data":{}},{"key":"456el","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"d8k97","text":" ","type":"atomic","depth":0,"inlineStyleRanges":[],"entityRanges":[{"offset":0,"length":1,"key":1}],"data":{}},{"key":"foi8s","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"fpnqp","text":" ","type":"atomic","depth":0,"inlineStyleRanges":[],"entityRanges":[{"offset":0,"length":1,"key":2}],"data":{}},{"key":"3mua1","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{"0":{"type":"IMAGE","mutability":"MUTABLE","data":{"src":"https://img.stibee.com/107_1626771509.png","height":"40px","width":"630px","alt":"ALIT"}},"1":{"type":"IMAGE","mutability":"MUTABLE","data":{"src":"https://img.stibee.com/107_1626771529.png","height":"295px","width":"600px","alt":"ALT"}},"2":{"type":"IMAGE","mutability":"MUTABLE","data":{"src":"https://img.stibee.com/107_1626771518.png","height":"40px","width":"630px","alt":"123"}}}}',
  },
  {
    id: 4,
    name: '5번템플릿',
    contents: '5번템플릿 내용입니다.',
    src: 'https://resource.stibee.com/templates/thumbnail/tem_news08.png',
    text: '5번템플릿관련된 컨텐츠인데 lorem',
  },
  {
    id: 5,
    name: '6번템플릿',
    contents: '6번템플릿 내용입니다.',
    src: 'https://resource.stibee.com/templates/thumbnail/tem_shop01.png',
    text: '6번템플릿관련된 컨텐츠인데 lorem',
  },
  {
    id: 6,
    name: '7번템플릿',
    contents: '7번템플릿 내용입니다.',
    src: 'https://resource.stibee.com/templates/thumbnail/tem_receipt01.png',
    text: '7번템플릿관련된 컨텐츠인데 lorem',
  },
  {
    id: 7,
    name: '8번템플릿',
    contents: '8번템플릿 내용입니다.',
    src: 'https://resource.stibee.com/templates/thumbnail/tem_essay02.png',
    text: '8번템플릿관련된 컨텐츠인데 lorem',
  },
  {
    id: 8,
    name: '9번템플릿',
    contents: '9번템플릿 내용입니다.',
    src: 'https://resource.stibee.com/templates/thumbnail/tem_news07.png',
    text: '9번템플릿관련된 컨텐츠인데 lorem',
  },
];
