export const EMAIL_TEMPLATE = [
  {
    id: 1,
    name: '빈템플릿',
    contents: '빈템플릿 내용입니다.',
    src: 'https://resource.stibee.com/templates/thumbnail/template_4.png',
    text: '{"blocks":[{"key":"9behp","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"82b35","text":" ","type":"atomic","depth":0,"inlineStyleRanges":[],"entityRanges":[{"offset":0,"length":1,"key":0}],"data":{}},{"key":"456el","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"d8k97","text":" ","type":"atomic","depth":0,"inlineStyleRanges":[],"entityRanges":[{"offset":0,"length":1,"key":1}],"data":{}},{"key":"foi8s","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"fpnqp","text":" ","type":"atomic","depth":0,"inlineStyleRanges":[],"entityRanges":[{"offset":0,"length":1,"key":2}],"data":{}},{"key":"3mua1","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{"0":{"type":"IMAGE","mutability":"MUTABLE","data":{"src":"https://img.stibee.com/107_1626771509.png","height":"40px","width":"630px","alt":"ALIT"}},"1":{"type":"IMAGE","mutability":"MUTABLE","data":{"src":"https://img.stibee.com/107_1626771529.png","height":"295px","width":"600px","alt":"ALT"}},"2":{"type":"IMAGE","mutability":"MUTABLE","data":{"src":"https://img.stibee.com/107_1626771518.png","height":"40px","width":"630px","alt":"123"}}}}',
  },
  {
    id: 2,
    name: '1번템플릿',
    contents: '1번템플릿 내용입니다.',
    src: 'https://resource.stibee.com/templates/thumbnail/template_1.png',
    text: '{"blocks":[{"key":"5ua09","text":"어쩌라는거에용","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}',
  },
  {
    id: 3,
    name: '2번템플릿',
    contents: '2번템플릿 내용입니다.',
    src: 'https://resource.stibee.com/templates/thumbnail/template_2.png',
    text: '{"blocks":[{"key":"5ua09","text":"2번 템플릿은 사직서","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}',
  },
  {
    id: 4,
    name: '3번템플릿',
    contents: '3번템플릿 내용입니다.',
    src: 'https://resource.stibee.com/templates/thumbnail/template_3.png',
    text: '',
  },
  {
    id: 5,
    name: '4번템플릿',
    contents: '4번템플릿 내용입니다.',
    src: 'https://resource.stibee.com/templates/thumbnail/tem_news09.png',
    text: '4번템플릿관련된 컨텐츠인데 lorem',
  },
  {
    id: 6,
    name: '5번템플릿',
    contents: '5번템플릿 내용입니다.',
    src: 'https://resource.stibee.com/templates/thumbnail/tem_news08.png',
    text: '5번템플릿관련된 컨텐츠인데 lorem',
  },
  {
    id: 7,
    name: '6번템플릿',
    contents: '6번템플릿 내용입니다.',
    src: 'https://resource.stibee.com/templates/thumbnail/tem_shop01.png',
    text: '6번템플릿관련된 컨텐츠인데 lorem',
  },
  {
    id: 8,
    name: '7번템플릿',
    contents: '7번템플릿 내용입니다.',
    src: 'https://resource.stibee.com/templates/thumbnail/tem_receipt01.png',
    text: '7번템플릿관련된 컨텐츠인데 lorem',
  },
  {
    id: 9,
    name: '8번템플릿',
    contents: '8번템플릿 내용입니다.',
    src: 'https://resource.stibee.com/templates/thumbnail/tem_essay02.png',
    text: '8번템플릿관련된 컨텐츠인데 lorem',
  },
  {
    id: 10,
    name: '9번템플릿',
    contents: '9번템플릿 내용입니다.',
    src: 'https://resource.stibee.com/templates/thumbnail/tem_news07.png',
    text: '9번템플릿관련된 컨텐츠인데 lorem',
  },
];
